#!/bin/env bash
#$HOME/.bash_aliases
alias ~='cd ~'
alias .='pwd'
alias ..='cd ..'
alias a='alias'
alias c='clear'
alias h='history'
alias j='jobs -l'
alias x='exit'
alias bc='bc -l'
alias bpi='for i in {1..3}; do bpi$i; done'
alias cdn='cd $HOME/Downloads'
alias du='du -kh'
alias df='df -kh'
alias diff='colordiff'
alias lh='find . -maxdepth 1 -name ".*" -ls'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mc='mc -b'
alias pv='pv -p'
alias mkdir='mkdir -pv'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias path='echo -e ${PATH//:/\\n}'
alias sue='sudo -e'
alias sui='sudo -i'
alias suvi='sudo visudo'
alias sumc='sudo mc'
alias mced='mcedit -b'
alias alidep='echo alias dependencies: bleachbit, cfv, colordiff, curl, hub, jq, pv, sipcalc'
alias sumced='sudo mcedit'
alias ipcalc='sipcalc'
alias lsnc='sudo lsof -n -P -i +c 15'
alias lsuser='cut -d: -f1 /etc/passwd'
alias userlist=lsuser
alias wget='curl -kLO#'
alias which='type -a'
case "$OS" in
    Darwin)
    	alias la='ls -AlG'
    	alias ll='ls -lG'
    	alias plb='/usr/libexec/PlistBuddy'
    	alias plu='plutil'
    	alias blkid='diskutil list'
    	alias md5sum='cfv -C -t md5'
    	alias md5sum-c='cfv -f'
    	alias netstat-l='netstat -anl -f inet'
    	alias netstat6-l='netstat -anl -f inet6'
    	alias git='hub'
    	alias grep='grep --colour'
    	alias egrep='egrep --colour'
    	alias fgrep='fgrep --colour'
    	for i in 1 224 256 384 512; do alias sha"$i"sum="shasum -a $i"; done
    	for i in 1 224 256 384 512; do alias sha"$i"sum-c="shasum -a $i -c"; done
    	alias shortcuts='open https://support.apple.com/en-us/HT201236'
    	alias updatedb='pushd /usr/libexec; sudo ./locate.updatedb; popd'
    	;;
    Linux)
    	alias bb='bleachbit'
    	alias subb='sudo bleachbit'
    	alias la='ls -Al --color=auto'
    	alias ll='ls -l --color=auto'
    	alias sc='systemctl'
    	alias sce='sudo crontab -e'
    	alias scq='systemctl list-units --type=service |more'
    	alias netstat-l='ss -anp -f inet'
    	alias netstat6-l='ss -anp -f inet6'
    	alias pbcopy='xsel --clipboard --input'
    	alias pbpaste='xsel --clipboard --output'
    	alias free='free -mt'
    	alias grep='grep --color=auto'
    	alias egrep='egrep --color=auto'
    	alias fgrep='fgrep --color=auto'
    	;;
esac
